### ISSUE TITLE
Can't add additional metas with SSR or Pre-render

### ISSUE THREAD

**Issue by acorcutt** [chiqui3d/stencil-head#1]
Hi, I can't add additional meta tags to the page from a component when using a hydrated ssr app or prerender (browser is ok)...

> TypeError: last.after is not a function at Meta.setMetas

However its fine modifying existing ones, see example and uncomment the og:title tag in index.html
https://github.com/acorcutt/stencil-ssr-now

There is a title on the page so it should still be finding a node to append to...
https://github.com/chiqui3d/stencil-head/blob/29024b75c6fd452a491e01579ef917e7f14e22c5/src/helper/meta.ts#L40

**Comment by chiqui3d** [comment]
Thank you. I'll get it fixed now.

**Comment by chiqui3d** [comment]
Fixed. Version 1.1.0. Reopen it if you find any other problems.
